[package]
name = "rustop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
nvml-wrapper = "0.9.0"
sysinfo = "0.28.4"
